import { MigrationInterface, QueryRunner } from "typeorm";

export class AddTaskCategories1778598554621 implements MigrationInterface {
    name = 'AddTaskCategories1778598554621'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "salary_rules" DROP CONSTRAINT "FK_salary_rules_user"`);
        await queryRunner.query(`ALTER TABLE "salary_rules" DROP CONSTRAINT "FK_salary_rules_family"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_users_family"`);
        await queryRunner.query(`ALTER TABLE "funds" DROP CONSTRAINT "FK_funds_owner"`);
        await queryRunner.query(`ALTER TABLE "funds" DROP CONSTRAINT "FK_funds_family"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_transactions_category"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_transactions_fund"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_transactions_user"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_transactions_family"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_categories_parent"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_categories_family"`);
        await queryRunner.query(`ALTER TABLE "anomalies" DROP CONSTRAINT "FK_anomalies_fund"`);
        await queryRunner.query(`ALTER TABLE "anomalies" DROP CONSTRAINT "FK_anomalies_category"`);
        await queryRunner.query(`ALTER TABLE "budgets" DROP CONSTRAINT "FK_budgets_category"`);
        await queryRunner.query(`ALTER TABLE "budgets" DROP CONSTRAINT "FK_budgets_fund"`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP CONSTRAINT "FK_chat_sessions_creator"`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP CONSTRAINT "FK_chat_sessions_fund"`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP CONSTRAINT "FK_chat_sessions_family"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_chat_messages_user"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_chat_messages_session"`);
        await queryRunner.query(`ALTER TABLE "families" DROP CONSTRAINT "FK_families_creator"`);
        await queryRunner.query(`ALTER TABLE "family_invitations" DROP CONSTRAINT "FK_invitations_creator"`);
        await queryRunner.query(`ALTER TABLE "family_invitations" DROP CONSTRAINT "FK_invitations_family"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP CONSTRAINT "FK_goals_user"`);
        await queryRunner.query(`ALTER TABLE "goals" DROP CONSTRAINT "FK_goals_family"`);
        await queryRunner.query(`ALTER TABLE "important_dates" DROP CONSTRAINT "FK_important_dates_creator"`);
        await queryRunner.query(`ALTER TABLE "important_dates" DROP CONSTRAINT "FK_important_dates_family"`);
        await queryRunner.query(`ALTER TABLE "yearly_ai_dates_cache" DROP CONSTRAINT "FK_yearly_ai_dates_cache_family"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_salary_rules_family"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_funds_family"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transactions_family"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transactions_fund_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transactions_user_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_categories_family"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_categories_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_chat_sessions_fund_last_msg"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_chat_sessions_creator_last_msg"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_chat_sessions_family"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_chat_messages_session_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invitations_family"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_goals_family"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_important_dates_family"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_important_dates_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_yearly_ai_dates_cache_family"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_insights_type_period_start"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."idx_tasks_family_id"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."idx_tasks_week_year"`);
        await queryRunner.query(`ALTER TABLE "yearly_ai_dates_cache" DROP CONSTRAINT "UQ_yearly_ai_dates_cache_family_year"`);
        await queryRunner.query(`ALTER TABLE "funds" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."funds_type_enum" AS ENUM('personal', 'joint')`);
        await queryRunner.query(`ALTER TABLE "funds" ADD "type" "public"."funds_type_enum" NOT NULL DEFAULT 'personal'`);
        await queryRunner.query(`ALTER TABLE "funds" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "funds" DROP COLUMN "purpose"`);
        await queryRunner.query(`CREATE TYPE "public"."funds_purpose_enum" AS ENUM('spending', 'savings', 'investment')`);
        await queryRunner.query(`ALTER TABLE "funds" ADD "purpose" "public"."funds_purpose_enum" NOT NULL DEFAULT 'spending'`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "source"`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_source_enum" AS ENUM('chat', 'form', 'photo', 'csv', 'recurring', 'salary')`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "source" "public"."transactions_source_enum" NOT NULL DEFAULT 'chat'`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "source" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "anomalies" DROP COLUMN "severity"`);
        await queryRunner.query(`CREATE TYPE "public"."anomalies_severity_enum" AS ENUM('low', 'medium', 'high')`);
        await queryRunner.query(`ALTER TABLE "anomalies" ADD "severity" "public"."anomalies_severity_enum" NOT NULL DEFAULT 'low'`);
        await queryRunner.query(`ALTER TABLE "anomalies" ALTER COLUMN "severity" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "budgets" DROP COLUMN "period"`);
        await queryRunner.query(`CREATE TYPE "public"."budgets_period_enum" AS ENUM('monthly', 'weekly')`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD "period" "public"."budgets_period_enum" NOT NULL DEFAULT 'monthly'`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP COLUMN "role"`);
        await queryRunner.query(`CREATE TYPE "public"."chat_messages_role_enum" AS ENUM('user', 'agent')`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD "role" "public"."chat_messages_role_enum" NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "goals" DROP COLUMN "period"`);
        await queryRunner.query(`CREATE TYPE "public"."goals_period_enum" AS ENUM('month', 'year')`);
        await queryRunner.query(`ALTER TABLE "goals" ADD "period" "public"."goals_period_enum" NOT NULL DEFAULT 'month'`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "period" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "goals" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."goals_type_enum" AS ENUM('save', 'spend_under')`);
        await queryRunner.query(`ALTER TABLE "goals" ADD "type" "public"."goals_type_enum" NOT NULL DEFAULT 'save'`);
        await queryRunner.query(`ALTER TABLE "goals" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "important_dates" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."important_dates_type_enum" AS ENUM('birthday', 'death_anniversary', 'anniversary', 'other')`);
        await queryRunner.query(`ALTER TABLE "important_dates" ADD "type" "public"."important_dates_type_enum" NOT NULL DEFAULT 'other'`);
        await queryRunner.query(`ALTER TABLE "insights" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."insights_type_enum" AS ENUM('daily', 'weekly', 'monthly', 'anomaly', 'big_buy', 'ad_hoc')`);
        await queryRunner.query(`ALTER TABLE "insights" ADD "type" "public"."insights_type_enum" NOT NULL DEFAULT 'ad_hoc'`);
        await queryRunner.query(`ALTER TABLE "insights" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TYPE "public"."task_category_enum" RENAME TO "task_category_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_category_enum" AS ENUM('shopping', 'chores', 'finance', 'goal', 'cooking', 'health', 'kids', 'transport')`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "category" TYPE "public"."tasks_category_enum" USING "category"::"text"::"public"."tasks_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."task_category_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."task_assignee_enum" RENAME TO "task_assignee_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_assignee_enum" AS ENUM('husband', 'wife', 'both')`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "assignee" TYPE "public"."tasks_assignee_enum" USING "assignee"::"text"::"public"."tasks_assignee_enum"`);
        await queryRunner.query(`DROP TYPE "public"."task_assignee_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."task_status_enum" RENAME TO "task_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_status_enum" AS ENUM('todo', 'in_progress', 'done')`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" TYPE "public"."tasks_status_enum" USING "status"::"text"::"public"."tasks_status_enum"`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" SET DEFAULT 'todo'`);
        await queryRunner.query(`DROP TYPE "public"."task_status_enum_old"`);
        await queryRunner.query(`CREATE INDEX "IDX_37a34f8133e18e8fb60209efad" ON "salary_rules" ("family_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_28ef42d5d7c91d44dad250fabc" ON "funds" ("family_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9fd8f88de499bf37f7b5aa0979" ON "transactions" ("family_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fe815e76e6d1e733cebfd0f903" ON "transactions" ("user_id", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e3fdd0182d41724fd5e39e5b2" ON "transactions" ("fund_id", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_eca48bc32f456d73e162478dfc" ON "categories" ("family_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b0be371d28245da6e4f4b6187" ON "categories" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_48f93e9a45424a842d63c22355" ON "chat_sessions" ("family_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cd3d7d3989b339aeefe214ba9c" ON "chat_sessions" ("created_by_id", "last_message_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_b4bccd781ae3fb44f8b1dba3e6" ON "chat_sessions" ("fund_id", "last_message_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_efbcf04c5086fabd02d6a0fb92" ON "chat_messages" ("session_id", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_f25f21826fe18167fd2ee1aeec" ON "family_invitations" ("family_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_64c76c99a7aa1060b75afb2995" ON "goals" ("family_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7879b3ba82df7dee63e8392746" ON "important_dates" ("family_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_88b0208953f7ad8fa77cab4992" ON "important_dates" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_24213e3b4e36b93f9e9ac9f6e2" ON "yearly_ai_dates_cache" ("family_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_04733061c86c6b9cdeff21f6b4" ON "yearly_ai_dates_cache" ("family_id", "year") `);
        await queryRunner.query(`CREATE INDEX "IDX_656252e1d7fad592ceacb01f56" ON "insights" ("type", "period_start") `);
        await queryRunner.query(`CREATE INDEX "IDX_fdf99afb2bad6d0b0b776eb2bc" ON "tasks" ("family_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cdac90ce2f5bec1c6aa410ce10" ON "tasks" ("week_year") `);
        await queryRunner.query(`ALTER TABLE "salary_rules" ADD CONSTRAINT "FK_ae588fd5c4b1f019260b2d8069f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "funds" ADD CONSTRAINT "FK_365fda657c455c020917a9bec3c" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_e9acc6efa76de013e8c1553ed2b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_5d5caaa3ab51a790c1404a0d77e" FOREIGN KEY ("fund_id") REFERENCES "funds"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_c9e41213ca42d50132ed7ab2b0f" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_88cea2dc9c31951d06437879b40" FOREIGN KEY ("parent_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anomalies" ADD CONSTRAINT "FK_db9df9097231c4cf09a1bb12e9f" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anomalies" ADD CONSTRAINT "FK_b86be338e846b0865940cb1efd6" FOREIGN KEY ("fund_id") REFERENCES "funds"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD CONSTRAINT "FK_4d1e7bba25cd32dbe7113c2b0d6" FOREIGN KEY ("fund_id") REFERENCES "funds"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD CONSTRAINT "FK_4bb589bf6db49e8c1fd6af05f49" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD CONSTRAINT "FK_ccc97021018571d6b7a2345d9e9" FOREIGN KEY ("fund_id") REFERENCES "funds"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD CONSTRAINT "FK_49853d0c8e7b7088de1d4ea8a31" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_0672782561e44d43febcfba2984" FOREIGN KEY ("session_id") REFERENCES "chat_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_5588b6cea298cedec7063c0d33e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goals" ADD CONSTRAINT "FK_88b78010581f2d293699d064441" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "goals" DROP CONSTRAINT "FK_88b78010581f2d293699d064441"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_5588b6cea298cedec7063c0d33e"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_0672782561e44d43febcfba2984"`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP CONSTRAINT "FK_49853d0c8e7b7088de1d4ea8a31"`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP CONSTRAINT "FK_ccc97021018571d6b7a2345d9e9"`);
        await queryRunner.query(`ALTER TABLE "budgets" DROP CONSTRAINT "FK_4bb589bf6db49e8c1fd6af05f49"`);
        await queryRunner.query(`ALTER TABLE "budgets" DROP CONSTRAINT "FK_4d1e7bba25cd32dbe7113c2b0d6"`);
        await queryRunner.query(`ALTER TABLE "anomalies" DROP CONSTRAINT "FK_b86be338e846b0865940cb1efd6"`);
        await queryRunner.query(`ALTER TABLE "anomalies" DROP CONSTRAINT "FK_db9df9097231c4cf09a1bb12e9f"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_88cea2dc9c31951d06437879b40"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_c9e41213ca42d50132ed7ab2b0f"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_5d5caaa3ab51a790c1404a0d77e"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_e9acc6efa76de013e8c1553ed2b"`);
        await queryRunner.query(`ALTER TABLE "funds" DROP CONSTRAINT "FK_365fda657c455c020917a9bec3c"`);
        await queryRunner.query(`ALTER TABLE "salary_rules" DROP CONSTRAINT "FK_ae588fd5c4b1f019260b2d8069f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cdac90ce2f5bec1c6aa410ce10"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fdf99afb2bad6d0b0b776eb2bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_656252e1d7fad592ceacb01f56"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_04733061c86c6b9cdeff21f6b4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_24213e3b4e36b93f9e9ac9f6e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88b0208953f7ad8fa77cab4992"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7879b3ba82df7dee63e8392746"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64c76c99a7aa1060b75afb2995"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f25f21826fe18167fd2ee1aeec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_efbcf04c5086fabd02d6a0fb92"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4bccd781ae3fb44f8b1dba3e6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd3d7d3989b339aeefe214ba9c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48f93e9a45424a842d63c22355"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b0be371d28245da6e4f4b6187"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eca48bc32f456d73e162478dfc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e3fdd0182d41724fd5e39e5b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe815e76e6d1e733cebfd0f903"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9fd8f88de499bf37f7b5aa0979"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_28ef42d5d7c91d44dad250fabc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37a34f8133e18e8fb60209efad"`);
        await queryRunner.query(`CREATE TYPE "public"."task_status_enum_old" AS ENUM('todo', 'in_progress', 'done')`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" TYPE "public"."task_status_enum_old" USING "status"::"text"::"public"."task_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "status" SET DEFAULT 'todo'`);
        await queryRunner.query(`DROP TYPE "public"."tasks_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."task_status_enum_old" RENAME TO "task_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."task_assignee_enum_old" AS ENUM('husband', 'wife', 'both')`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "assignee" TYPE "public"."task_assignee_enum_old" USING "assignee"::"text"::"public"."task_assignee_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_assignee_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."task_assignee_enum_old" RENAME TO "task_assignee_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."task_category_enum_old" AS ENUM('shopping', 'chores', 'finance', 'goal')`);
        await queryRunner.query(`ALTER TABLE "tasks" ALTER COLUMN "category" TYPE "public"."task_category_enum_old" USING "category"::"text"::"public"."task_category_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_category_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."task_category_enum_old" RENAME TO "task_category_enum"`);
        await queryRunner.query(`ALTER TABLE "insights" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."insights_type_enum"`);
        await queryRunner.query(`ALTER TABLE "insights" ADD "type" character varying(16) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "important_dates" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."important_dates_type_enum"`);
        await queryRunner.query(`ALTER TABLE "important_dates" ADD "type" character varying(32) NOT NULL DEFAULT 'other'`);
        await queryRunner.query(`ALTER TABLE "goals" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."goals_type_enum"`);
        await queryRunner.query(`ALTER TABLE "goals" ADD "type" character varying(16) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "goals" DROP COLUMN "period"`);
        await queryRunner.query(`DROP TYPE "public"."goals_period_enum"`);
        await queryRunner.query(`ALTER TABLE "goals" ADD "period" character varying(8) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."chat_messages_role_enum"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD "role" character varying(8) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "budgets" DROP COLUMN "period"`);
        await queryRunner.query(`DROP TYPE "public"."budgets_period_enum"`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD "period" character varying(8) NOT NULL DEFAULT 'monthly'`);
        await queryRunner.query(`ALTER TABLE "anomalies" DROP COLUMN "severity"`);
        await queryRunner.query(`DROP TYPE "public"."anomalies_severity_enum"`);
        await queryRunner.query(`ALTER TABLE "anomalies" ADD "severity" character varying(8) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "source"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_source_enum"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "source" character varying(16) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "funds" DROP COLUMN "purpose"`);
        await queryRunner.query(`DROP TYPE "public"."funds_purpose_enum"`);
        await queryRunner.query(`ALTER TABLE "funds" ADD "purpose" character varying(16) NOT NULL DEFAULT 'spending'`);
        await queryRunner.query(`ALTER TABLE "funds" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."funds_type_enum"`);
        await queryRunner.query(`ALTER TABLE "funds" ADD "type" character varying(16) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "yearly_ai_dates_cache" ADD CONSTRAINT "UQ_yearly_ai_dates_cache_family_year" UNIQUE ("family_id", "year")`);
        await queryRunner.query(`CREATE INDEX "idx_tasks_week_year" ON "tasks" ("week_year") `);
        await queryRunner.query(`CREATE INDEX "idx_tasks_family_id" ON "tasks" ("family_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_insights_type_period_start" ON "insights" ("type", "period_start") `);
        await queryRunner.query(`CREATE INDEX "IDX_yearly_ai_dates_cache_family" ON "yearly_ai_dates_cache" ("family_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_important_dates_date" ON "important_dates" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_important_dates_family" ON "important_dates" ("family_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_goals_family" ON "goals" ("family_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_invitations_family" ON "family_invitations" ("family_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_chat_messages_session_created_at" ON "chat_messages" ("session_id", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_chat_sessions_family" ON "chat_sessions" ("family_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_chat_sessions_creator_last_msg" ON "chat_sessions" ("created_by_id", "last_message_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_chat_sessions_fund_last_msg" ON "chat_sessions" ("fund_id", "last_message_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_categories_name" ON "categories" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_categories_family" ON "categories" ("family_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_transactions_user_date" ON "transactions" ("user_id", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_transactions_fund_date" ON "transactions" ("fund_id", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_transactions_family" ON "transactions" ("family_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_funds_family" ON "funds" ("family_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_salary_rules_family" ON "salary_rules" ("family_id") `);
        await queryRunner.query(`ALTER TABLE "yearly_ai_dates_cache" ADD CONSTRAINT "FK_yearly_ai_dates_cache_family" FOREIGN KEY ("family_id") REFERENCES "families"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "important_dates" ADD CONSTRAINT "FK_important_dates_family" FOREIGN KEY ("family_id") REFERENCES "families"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "important_dates" ADD CONSTRAINT "FK_important_dates_creator" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goals" ADD CONSTRAINT "FK_goals_family" FOREIGN KEY ("family_id") REFERENCES "families"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goals" ADD CONSTRAINT "FK_goals_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "family_invitations" ADD CONSTRAINT "FK_invitations_family" FOREIGN KEY ("family_id") REFERENCES "families"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "family_invitations" ADD CONSTRAINT "FK_invitations_creator" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "families" ADD CONSTRAINT "FK_families_creator" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_chat_messages_session" FOREIGN KEY ("session_id") REFERENCES "chat_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_chat_messages_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD CONSTRAINT "FK_chat_sessions_family" FOREIGN KEY ("family_id") REFERENCES "families"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD CONSTRAINT "FK_chat_sessions_fund" FOREIGN KEY ("fund_id") REFERENCES "funds"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD CONSTRAINT "FK_chat_sessions_creator" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD CONSTRAINT "FK_budgets_fund" FOREIGN KEY ("fund_id") REFERENCES "funds"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD CONSTRAINT "FK_budgets_category" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anomalies" ADD CONSTRAINT "FK_anomalies_category" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "anomalies" ADD CONSTRAINT "FK_anomalies_fund" FOREIGN KEY ("fund_id") REFERENCES "funds"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_categories_family" FOREIGN KEY ("family_id") REFERENCES "families"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_categories_parent" FOREIGN KEY ("parent_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_transactions_family" FOREIGN KEY ("family_id") REFERENCES "families"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_transactions_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_transactions_fund" FOREIGN KEY ("fund_id") REFERENCES "funds"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_transactions_category" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "funds" ADD CONSTRAINT "FK_funds_family" FOREIGN KEY ("family_id") REFERENCES "families"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "funds" ADD CONSTRAINT "FK_funds_owner" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_users_family" FOREIGN KEY ("family_id") REFERENCES "families"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salary_rules" ADD CONSTRAINT "FK_salary_rules_family" FOREIGN KEY ("family_id") REFERENCES "families"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salary_rules" ADD CONSTRAINT "FK_salary_rules_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
